//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUunStokProjesi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcUrunstokEntities2 : DbContext
    {
        public MvcUrunstokEntities2()
            : base("name=MvcUrunstokEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblkotegoriler> tblkotegoriler { get; set; }
        public virtual DbSet<tblmusteriler> tblmusteriler { get; set; }
        public virtual DbSet<tblsatişlar> tblsatişlar { get; set; }
        public virtual DbSet<tblurunler> tblurunler { get; set; }
    }
}
