//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUunStokProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblmusteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblmusteriler()
        {
            this.tblsatişlar = new HashSet<tblsatişlar>();
        }
    
        public int musteriid { get; set; }

        [Required(ErrorMessage ="Bu Alanı Boş Bırakamazsınız...")]
        [StringLength(50,ErrorMessage ="En Fazla 50 Karekterlik İsim Girin")]
        public string musteriad { get; set; }
        public string musterisoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatişlar> tblsatişlar { get; set; }
    }
}
