//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUunStokProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblurunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblurunler()
        {
            this.tblsatişlar = new HashSet<tblsatişlar>();
        }
    
        public int urunid { get; set; }
        public string urunad { get; set; }
        public string marka { get; set; }
        public Nullable<short> urunkategori { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<byte> stok { get; set; }
    
        public virtual tblkotegoriler tblkotegoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsatişlar> tblsatişlar { get; set; }
    }
}
